### ISSUE TITLE
Error 1033 from Cloudflare when querying data.

### ISSUE THREAD

**Issue by ShikiSuen** [torikushiii/hoyoverse-api#1]
Tested link:
```
https://api.ennead.cc/mihoyo/starrail/news/info?lang=en
```

Result:

<img width="1175" alt="image" src="https://github.com/user-attachments/assets/203b0b58-2160-42b7-9e00-c43a47e27690">

**Comment by torikushiii** [comment]
Yeah sorry about that, my server went down and I didn't notice it, should be all good now.

**Comment by ShikiSuen** [comment]
@torikushiii No problem.

If I were you I might set up another repository with GitHub CI bot to monitor the API servicing status. This can automatically detect such issues (with GitHub notifications when errors happened).

**Comment by torikushiii** [comment]
Yeah, thanks for the suggestion, I'll try setting up something like that~
