### ISSUE TITLE
Can image url be added for the events?

### ISSUE THREAD

**Issue by Nubuki-all** [torikushiii/hoyoverse-api#2]
Pls add an image field for each event if possible

**Comment by torikushiii** [comment]
for  `/calender` endpoint? If so, I'll see how since their API doesn't return any of image banners...

**Comment by Nubuki-all** [comment]
Yes

**Comment by torikushiii** [comment]
After searching around, unfortunately there is no easy way to get the image url for each event since there's no API endpoint that returns the image url for events.

But feel free to comment here and let me know if you find a way to get the image url for each event.

**Comment by Nubuki-all** [comment]
A long shot but how about scraping the genshin wiki for the image

**Comment by torikushiii** [comment]
as of this commit 6d157f4, all calendar URL's now return event images. The response object would look like this with the new `image_url` property

```json

  "events": [
    {
      "id": 66,
      "name": "Gift of Odyssey",
      "description": "",
      "image_url": "https://static.wikia.nocookie.net/houkai-star-rail/images/9/96/Event_Gift_of_Odyssey_2024-12-04.png/revision/latest/scale-to-width-down/1000?cb=20241122215818",
      "type_name": "ActivityTypeSign",
      "start_time": 1733108400,
      "end_time": 1736823599,
      "rewards": [
        {
          "id": 102,
          "name": "Star Rail Special Pass",
          "icon": "https://act-webstatic.hoyoverse.com/darkmatter/hkrpg/prod_gf_cn/item_icon_u542tc/050ede0a85d5a9e3bb3c31a9131a770c.png",
          "rarity": "5",
          "amount": 10
        }
      ],
      "special_reward": {
        "id": 102,
        "name": "Star Rail Special Pass",
        "icon": "https://act-webstatic.hoyoverse.com/darkmatter/hkrpg/prod_gf_cn/item_icon_u542tc/050ede0a85d5a9e3bb3c31a9131a770c.png",
        "rarity": "5",
        "amount": 10
      }
    }
  }
]
``` 

Let me know if there's something wrong.

**Comment by Nubuki-all** [comment]
Great
Since you are already scraping the wiki 
Can you get the start_time & end_time for upcoming events too

**Comment by torikushiii** [comment]
~~the API already gave this data (`start_time`, `end_time`).~~

~~unless you mean something else?~~

nvm, apparently Genshin does not return any start and end time, I was looking at Star Rail calendar and it returns  the upcoming events just fine. I'll take a look into it I guess

**Comment by torikushiii** [comment]
latest commit should fix the upcoming events dates returned `0`.

**Comment by Nubuki-all** [comment]
Thank you 
That would be all
